version: '3'
services:
  clinvap_db:
    image: mongo 
  clinvap_example_data:
    image: clinvap/report_db_api_example_data
    depends_on:
      - 'clinvap_db'
    links:
      - 'clinvap_db:db'
  clinvap:
    image: clinvap/report_db_api
    depends_on:
      - 'clinvap_example_data'
    links: 
      - 'clinvap_db:db'
  db:
    image: mongo
  db_api:
    image: clinvap_net/db
    build:
      context: ./db 
      dockerfile: ./db/Dockerfile
    environment:
      ENV: DEV
    depends_on:
      - 'db'
    links:
      - 'db'
    ports:
      - '3001:5001'
  api:
    image: clinvap_net/api
    build: .
    environment:
      ENV: DEV
    volumes:
      - .:/api
    depends_on:
      - 'clinvap'
    links:
      - 'clinvap'
    ports:
      - '3000:3000'
